FROM php:7.1-alpine
LABEL Maintainer="Asdrubal Gonzalez <agpenton@gmail.com"
RUN apk --update add wget curl git php php-curl php-openssl php-json php-phar php-dom libsodium-dev libxslt-dev libpng-dev zlib-dev libxml2-dev icu-dev g++ libxml2-dev freetype-dev libpng-dev libjpeg-turbo-dev g++ make autoconf bash sshpass git openssh-client rsync && rm /var/cache/apk/* && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && curl -LO https://deployer.org/deployer.phar && mv deployer.phar /usr/local/bin/dep && chmod +x /usr/local/bin/dep
RUN pecl install redis libsodium && docker-php-ext-enable redis sodium
RUN docker-php-ext-configure intl && docker-php-ext-install intl
#RUN docker-php-source extract && pecl install redis libsodium && docker-php-ext-enable redis sodium
#RUN pecl install redis libsodium && docker-php-ext-enable redis sodium
RUN set -x \
    apk add --no-cache freetype-dev libjpeg-turbo-dev libpng-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd
RUN docker-php-ext-install mbstring zip gd bcmath soap pdo_mysql mysqli pcntl xsl
RUN apk add	 --no-cache libmcrypt-dev && docker-php-ext-configure mcrypt --with-mcrypt && docker-php-ext-install mcrypt
CMD ["/bin/sh"]

ENTRYPOINT ["/bin/sh", "-c"]
